// AUTO-GENERATED by scripts/select-brand.mjs — do not edit by hand.
// Regenerate with `pnpm select-brand` (or let the predev/prebuild hooks do
// it). Source of truth: branding/${BRAND}/brand.json, or Clovy's own
// defaults in scripts/select-brand.mjs when BRAND is unset.

export const BRAND_ID = "bonzai";
export const BRAND_NAME = "Bonzai";
export const BRAND_ACCENT = "#0000D2";
export const BRAND_ACCENT_WASH = "#2d2db5";
export const BRAND_SUPPORT_TEXT = "the Bonzai team";
