#!/usr/bin/env node

// Whitelabel prebuild step (docs/whitelabel-implementation-plan.md, ADR-0056).
// Writes the gitignored src/lib/brand.generated.ts from either
// branding/<BRAND>/brand.json (when BRAND is set) or Clovy's own defaults
// (when it isn't). Runs automatically before `pnpm dev` / `pnpm build` via
// the predev/prebuild package.json hooks, so a plain checkout with no BRAND
// set always regenerates today's Clovy identity and needs no setup.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_PATH = resolve(ROOT_DIR, "src", "lib", "brand.generated.ts");

// Mirrors today's shipped Clovy identity — the fallback when BRAND is unset,
// and the shape branding/<brand-id>/brand.json overrides. accent/accentWash
// mirror the "sage" preset in src/lib/brand.ts (unused by Clovy's own build,
// since BRAND_ID === "clovy" skips the whitelabel-default accent path
// entirely — see initBrand() in that file).
const CLOVY_DEFAULTS = {
  id: "clovy",
  productName: "Clovy",
  accent: "#3f812f",
  accentWash: "#5a7c56",
  supportText: "the Clovy team",
};

function loadBrand(brandId) {
  if (!brandId) {
    return CLOVY_DEFAULTS;
  }
  const brandJsonPath = resolve(ROOT_DIR, "branding", brandId, "brand.json");
  if (!existsSync(brandJsonPath)) {
    console.error(
      `BRAND=${brandId} was requested but ${brandJsonPath} does not exist. See branding/README.md.`,
    );
    process.exit(1);
  }
  const brand = JSON.parse(readFileSync(brandJsonPath, "utf8"));
  for (const field of ["productName", "accent", "supportText"]) {
    if (typeof brand[field] !== "string" || brand[field].length === 0) {
      console.error(`${brandJsonPath} is missing required field "${field}".`);
      process.exit(1);
    }
  }
  // accentWash is optional: falls back to accent itself (a valid, if less
  // refined, wash — see branding/README.md's accent/accentWash note).
  return { id: brand.id ?? brandId, ...brand, accentWash: brand.accentWash || brand.accent };
}

const brand = loadBrand(process.env.BRAND);

const contents = `// AUTO-GENERATED by scripts/select-brand.mjs — do not edit by hand.
// Regenerate with \`pnpm select-brand\` (or let the predev/prebuild hooks do
// it). Source of truth: branding/\${BRAND}/brand.json, or Clovy's own
// defaults in scripts/select-brand.mjs when BRAND is unset.

export const BRAND_ID = ${JSON.stringify(brand.id)};
export const BRAND_NAME = ${JSON.stringify(brand.productName)};
export const BRAND_ACCENT = ${JSON.stringify(brand.accent)};
export const BRAND_ACCENT_WASH = ${JSON.stringify(brand.accentWash)};
export const BRAND_SUPPORT_TEXT = ${JSON.stringify(brand.supportText)};
`;

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, contents);
console.error(`Wrote ${OUTPUT_PATH} for brand "${brand.id}".`);
